import 'package:freezed_annotation/freezed_annotation.dart';

part 'project.freezed.dart';
part 'project.g.dart';

/// Project Data Model
///
/// This model represents a fermentation project in the Fermentrack app.
/// It uses Freezed for immutability and code generation, which provides:
/// - Immutable data classes
/// - copyWith() method for updates
/// - Equality comparison
/// - toString() implementation
/// - JSON serialization/deserialization
///
/// Learning Points:
/// - Freezed package for immutable models
/// - JSON serialization with json_serializable
/// - Enums for type-safe values
/// - DateTime handling in Dart
/// - Null safety patterns
///
/// Architecture Notes:
/// - This is a pure data model with no business logic
/// - Immutability ensures thread safety and prevents bugs
/// - JSON serialization enables Firestore integration
/// - Enums provide type safety for status and type fields
@freezed
class Project with _$Project {
  /// Constructor for Project model
  ///
  /// Parameters:
  /// - [id]: Unique identifier (nullable for new projects before Firestore assigns ID)
  /// - [name]: Project name (required)
  /// - [type]: Type of fermentation project (required)
  /// - [startDate]: When the project started (required)
  /// - [endDate]: When the project completed (optional)
  /// - [userId]: ID of the user who owns this project (required)
  /// - [status]: Current status of the project (required)
  /// - [description]: Optional description of the project
  const factory Project({
    /// Unique identifier from Firestore
    /// Null for new projects that haven't been saved yet
    String? id,

    /// Name of the fermentation project
    /// Example: "My First Sourdough", "Summer Kombucha Batch"
    required String name,

    /// Type of fermentation project
    /// Determines icon and specific features available
    required ProjectType type,

    /// Date when fermentation started
    /// Used to calculate "days active" and track progress
    required DateTime startDate,

    /// Date when fermentation ended (optional)
    /// Null for active projects, set when project is completed
    DateTime? endDate,

    /// User ID of the project owner
    /// Used for user-specific data isolation in Firestore
    required String userId,

    /// Current status of the project
    /// Determines display and available actions
    @Default(ProjectStatus.active) ProjectStatus status,

    /// Optional description or notes about the project
    /// Example: "Using whole wheat flour, 75% hydration"
    String? description,
  }) = _Project;

  /// Create Project from JSON
  ///
  /// This factory constructor enables deserialization from Firestore
  /// and other JSON sources. Generated by json_serializable.
  factory Project.fromJson(Map<String, dynamic> json) =>
      _$ProjectFromJson(json);
}

/// Project Type Enum
///
/// Represents different types of fermentation projects supported by the app.
/// Each type may have specific features, templates, and tracking options.
///
/// Learning Points:
/// - Enums provide type safety
/// - @JsonEnum enables JSON serialization
/// - Descriptive names improve code readability
///
/// Future Enhancements:
/// - Add more fermentation types (beer, wine, pickles, etc.)
/// - Add custom icons per type
/// - Add type-specific data models
@JsonEnum()
enum ProjectType {
  /// Sourdough bread fermentation
  /// Tracks starter health, feeding schedule, bake logs
  sourdough,

  /// Kombucha fermentation
  /// Tracks SCOBY health, flavor combinations, carbonation
  kombucha,

  /// Kimchi fermentation
  /// Tracks vegetable types, spice levels, fermentation progress
  kimchi,

  /// Water kefir fermentation
  /// Tracks grain health, flavor additions, carbonation
  waterKefir,

  /// Yogurt fermentation
  /// Tracks culture type, temperature, consistency
  yogurt,

  /// Sauerkraut fermentation
  /// Tracks cabbage type, salt ratio, fermentation progress
  sauerkraut,

  /// Generic/other fermentation projects
  /// For types not explicitly listed above
  other,
}

/// Project Status Enum
///
/// Represents the lifecycle status of a fermentation project.
/// Determines what actions are available and how the project is displayed.
///
/// Learning Points:
/// - State management through enums
/// - Lifecycle tracking
/// - UI conditional rendering based on status
@JsonEnum()
enum ProjectStatus {
  /// Project is currently active and being monitored
  /// Default status for new projects
  active,

  /// Project is temporarily paused
  /// Data logging is disabled but can be resumed
  paused,

  /// Project has been completed successfully
  /// Historical data is preserved but no new data is added
  completed,

  /// Project was archived
  /// Removed from active views but data is preserved
  archived,
}
