// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBRX06fcxs_c5z70Xvem7lzpsLUj-9I7Q',
    appId: '1:1006513012406:web:ae7d374ceecaab08eb3017',
    messagingSenderId: '1006513012406',
    projectId: 'long-centaur-293520',
    authDomain: 'long-centaur-293520.firebaseapp.com',
    storageBucket: 'long-centaur-293520.firebasestorage.app',
    measurementId: 'G-83XC0LGYRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr-43whXnYiA9C7EwckSvkhvXnrcc8THE',
    appId: '1:1006513012406:android:72260c23e147f0a4eb3017',
    messagingSenderId: '1006513012406',
    projectId: 'long-centaur-293520',
    storageBucket: 'long-centaur-293520.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjO3IaXGFyjaRPCjnTbteDDRLLivggBk0',
    appId: '1:1006513012406:ios:fd557cfa775a288eeb3017',
    messagingSenderId: '1006513012406',
    projectId: 'long-centaur-293520',
    storageBucket: 'long-centaur-293520.firebasestorage.app',
    iosBundleId: 'com.example.fermentrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjO3IaXGFyjaRPCjnTbteDDRLLivggBk0',
    appId: '1:1006513012406:ios:fd557cfa775a288eeb3017',
    messagingSenderId: '1006513012406',
    projectId: 'long-centaur-293520',
    storageBucket: 'long-centaur-293520.firebasestorage.app',
    iosBundleId: 'com.example.fermentrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBRX06fcxs_c5z70Xvem7lzpsLUj-9I7Q',
    appId: '1:1006513012406:web:cf23f4840eddfeb9eb3017',
    messagingSenderId: '1006513012406',
    projectId: 'long-centaur-293520',
    authDomain: 'long-centaur-293520.firebaseapp.com',
    storageBucket: 'long-centaur-293520.firebasestorage.app',
    measurementId: 'G-V21V24F73C',
  );
}
