name: Flutter Tests

on:
  pull_request:
    branches: 
        - main # Triggers on pull requests targeting main branch
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  test:
    runs-on: ubuntu-latest # Specifies the operating system for the job

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Clones your repository into the workflow environment

      - name: Set up Flutter
        uses: subosito/flutter-action@v2 # Sets up the Flutter SDK
        with:
          channel: 'stable' # Specifies the Flutter channel (e.g., stable, beta, master)

      - name: Install Flutter Dependencies
        run: flutter pub get # Fetches all dependencies specified in pubspec.yaml

      - name: Run Flutter Tests
        run: flutter test --coverage # Executes all unit and widget tests and generates a coverage report

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@6c1aa0cc9e1c02f9f58f01ac599f1064ccc83470

      - name: Comment Code Coverage
        uses: zgosalvez/github-actions-report-lcov@55c5634f4f1085c376473dfd5971662ced3b9dc1
        with:
            coverage-files: fermentrack/coverage/lcov.info
            github-token: ${{ secrets.GITHUB_TOKEN }}
            minimum-coverage: 60 # Optional: Fails if coverage drops below this percentage
            update-comment: true
